version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: newshub-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: newshub
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - newshub-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: newshub-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - newshub-network

  # API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newshub-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGO_URI: mongodb://admin:password@mongodb:27017/newshub?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      AI_API_KEY: your-ai-api-key
      PLAGIARISM_API_KEY: your-plagiarism-api-key
      FRONTEND_URL: http://localhost:3000
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - newshub-network

  # Worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: newshub-worker
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://admin:password@mongodb:27017/newshub?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      AI_API_KEY: your-ai-api-key
      PLAGIARISM_API_KEY: your-plagiarism-api-key
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - newshub-network

  # Nginx (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: newshub-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - newshub-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  newshub-network:
    driver: bridge